import { ILocation } from '../models/ILocation';

export const MOCK_DATA: ILocation[] = [
    {
        Id: 1,
        Title: 'Headquarters',
        State: 'TX',
        Branch: 'Austin Main',
        Street: '123 Enterprise Blvd',
        City: 'Austin',
        Zip: '78701',
        Country: 'USA',
        Contact: 'John Smith',
        Phone: '512-555-0101',
        DistrictManager: 'Sarah Connor',
        Active: true,
        Latitude: 30.2672,
        Longitude: -97.7431,
        BuildingSqft: 25000,
        LotSqft: 50000,
        ParkingSpots: 120,
        YearBuilt: 1995,
        BlueprintUrl: { Description: 'HQ Blueprint', Url: 'https://pdfobject.com/pdf/sample.pdf' },
        FloorplanUrl: { Description: 'HQ Floorplan', Url: 'https://pdfobject.com/pdf/sample.pdf' },
        DocsFolderUrl: { Description: 'HQ Docs', Url: '#' },
        Modified: '2023-10-01T10:00:00Z'
    },
    {
        Id: 2,
        Title: 'Dallas North Branch',
        State: 'TX',
        Branch: 'Dallas North',
        Street: '456 Tech Way',
        City: 'Dallas',
        Zip: '75201',
        Country: 'USA',
        Contact: 'Mike Ross',
        Phone: '214-555-0102',
        DistrictManager: 'Harvey Specter',
        Active: true,
        Latitude: 32.7767,
        Longitude: -96.7970,
        BuildingSqft: 15000,
        LotSqft: 30000,
        ParkingSpots: 80,
        YearBuilt: 2005,
        BlueprintUrl: null, // Test missing blueprint
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-09-15T14:30:00Z'
    },
    {
        Id: 3,
        Title: 'Houston South Hub',
        State: 'TX',
        Branch: 'Houston South',
        Street: '789 Energy Dr',
        City: 'Houston',
        Zip: '77001',
        Country: 'USA',
        Contact: 'Jessica Pearson',
        Phone: '713-555-0103',
        DistrictManager: 'Louis Litt',
        Active: true,
        Latitude: 29.7604,
        Longitude: -95.3698,
        BuildingSqft: 20000,
        LotSqft: 40000,
        ParkingSpots: 100,
        YearBuilt: 2010,
        BlueprintUrl: { Description: 'Houston Blueprint', Url: 'https://pdfobject.com/pdf/sample.pdf' },
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-10-05T09:15:00Z'
    },
    {
        Id: 4,
        Title: 'San Antonio West',
        State: 'TX',
        Branch: 'San Antonio West',
        Street: '321 Alamo St',
        City: 'San Antonio',
        Zip: '78201',
        Country: 'USA',
        Contact: 'Rachel Zane',
        Phone: '210-555-0104',
        DistrictManager: 'Harvey Specter',
        Active: false,
        Latitude: 29.4241,
        Longitude: -98.4936,
        BuildingSqft: 12000,
        LotSqft: 25000,
        ParkingSpots: 60,
        YearBuilt: 1980,
        BlueprintUrl: null,
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-08-20T11:00:00Z'
    },
    {
        Id: 5,
        Title: 'Miami Beach Office',
        State: 'FL',
        Branch: 'Miami Beach',
        Street: '555 Ocean Dr',
        City: 'Miami Beach',
        Zip: '33139',
        Country: 'USA',
        Contact: 'Sonny Crockett',
        Phone: '305-555-0105',
        DistrictManager: 'Ricardo Tubbs',
        Active: true,
        Latitude: 25.7907,
        Longitude: -80.1300,
        BuildingSqft: 18000,
        LotSqft: 35000,
        ParkingSpots: 90,
        YearBuilt: 2015,
        BlueprintUrl: { Description: 'Miami Blueprint', Url: 'https://pdfobject.com/pdf/sample.pdf' },
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-10-10T16:45:00Z'
    },
    {
        Id: 6,
        Title: 'Orlando Central',
        State: 'FL',
        Branch: 'Orlando Central',
        Street: '888 Disney Way',
        City: 'Orlando',
        Zip: '32801',
        Country: 'USA',
        Contact: 'Mickey Mouse',
        Phone: '407-555-0106',
        DistrictManager: 'Ricardo Tubbs',
        Active: true,
        Latitude: 28.5383,
        Longitude: -81.3792,
        BuildingSqft: 22000,
        LotSqft: 45000,
        ParkingSpots: 110,
        YearBuilt: 2000,
        BlueprintUrl: null,
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-09-25T13:20:00Z'
    },
    {
        Id: 7,
        Title: 'Tampa Bay Logistics',
        State: 'FL',
        Branch: 'Tampa Bay',
        Street: '777 Bay Blvd',
        City: 'Tampa',
        Zip: '33601',
        Country: 'USA',
        Contact: 'Tom Brady',
        Phone: '813-555-0107',
        DistrictManager: 'Ricardo Tubbs',
        Active: true,
        Latitude: 27.9506,
        Longitude: -82.4572,
        BuildingSqft: 30000,
        LotSqft: 60000,
        ParkingSpots: 150,
        YearBuilt: 2018,
        BlueprintUrl: { Description: 'Tampa Blueprint', Url: 'https://pdfobject.com/pdf/sample.pdf' },
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-10-12T08:30:00Z'
    },
    {
        Id: 8,
        Title: 'Los Angeles Downtown',
        State: 'CA',
        Branch: 'LA Metro',
        Street: '101 Hollywood Blvd',
        City: 'Los Angeles',
        Zip: '90001',
        Country: 'USA',
        Contact: 'Tony Stark',
        Phone: '213-555-0108',
        DistrictManager: 'Nick Fury',
        Active: true,
        Latitude: 34.0522,
        Longitude: -118.2437,
        BuildingSqft: 40000,
        LotSqft: 80000,
        ParkingSpots: 200,
        YearBuilt: 2012,
        BlueprintUrl: { Description: 'LA Blueprint', Url: 'https://pdfobject.com/pdf/sample.pdf' },
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-10-08T15:00:00Z'
    },
    {
        Id: 9,
        Title: 'San Francisco Tech Hub',
        State: 'CA',
        Branch: 'SF Bay Area',
        Street: '500 Market St',
        City: 'San Francisco',
        Zip: '94101',
        Country: 'USA',
        Contact: 'Steve Jobs',
        Phone: '415-555-0109',
        DistrictManager: 'Nick Fury',
        Active: true,
        Latitude: 37.7749,
        Longitude: -122.4194,
        BuildingSqft: 35000,
        LotSqft: 70000,
        ParkingSpots: 100,
        YearBuilt: 2016,
        BlueprintUrl: null,
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-09-30T10:45:00Z'
    },
    {
        Id: 10,
        Title: 'San Diego Naval Base',
        State: 'CA',
        Branch: 'San Diego South',
        Street: '200 Navy Pier',
        City: 'San Diego',
        Zip: '92101',
        Country: 'USA',
        Contact: 'Maverick',
        Phone: '619-555-0110',
        DistrictManager: 'Nick Fury',
        Active: true,
        Latitude: 32.7157,
        Longitude: -117.1611,
        BuildingSqft: 28000,
        LotSqft: 55000,
        ParkingSpots: 130,
        YearBuilt: 1990,
        BlueprintUrl: { Description: 'SD Blueprint', Url: 'https://pdfobject.com/pdf/sample.pdf' },
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-10-14T12:00:00Z'
    },
    {
        Id: 11,
        Title: 'New York Midtown',
        State: 'NY',
        Branch: 'NYC Metro',
        Street: '350 5th Ave',
        City: 'New York',
        Zip: '10118',
        Country: 'USA',
        Contact: 'Peter Parker',
        Phone: '212-555-0111',
        DistrictManager: 'May Parker',
        Active: true,
        Latitude: 40.7128,
        Longitude: -74.0060,
        BuildingSqft: 50000,
        LotSqft: 10000, // NYC lots are small!
        ParkingSpots: 0,
        YearBuilt: 1930,
        BlueprintUrl: { Description: 'NYC Blueprint', Url: 'https://pdfobject.com/pdf/sample.pdf' },
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-10-02T09:00:00Z'
    },
    {
        Id: 12,
        Title: 'Albany State Capital',
        State: 'NY',
        Branch: 'Upstate NY',
        Street: '100 State St',
        City: 'Albany',
        Zip: '12207',
        Country: 'USA',
        Contact: 'Hamilton',
        Phone: '518-555-0112',
        DistrictManager: 'May Parker',
        Active: true,
        Latitude: 42.6526,
        Longitude: -73.7562,
        BuildingSqft: 20000,
        LotSqft: 40000,
        ParkingSpots: 80,
        YearBuilt: 1985,
        BlueprintUrl: null,
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-09-20T14:15:00Z'
    },
    {
        Id: 13,
        Title: 'Buffalo West',
        State: 'NY',
        Branch: 'Upstate NY',
        Street: '500 Main St',
        City: 'Buffalo',
        Zip: '14202',
        Country: 'USA',
        Contact: 'Josh Allen',
        Phone: '716-555-0113',
        DistrictManager: 'May Parker',
        Active: true,
        Latitude: 42.8864,
        Longitude: -78.8784,
        BuildingSqft: 25000,
        LotSqft: 50000,
        ParkingSpots: 100,
        YearBuilt: 2008,
        BlueprintUrl: { Description: 'Buffalo Blueprint', Url: 'https://pdfobject.com/pdf/sample.pdf' },
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-10-18T11:30:00Z'
    },
    {
        Id: 14,
        Title: 'Chicago Loop',
        State: 'IL',
        Branch: 'Chicago Metro',
        Street: '200 W Jackson Blvd',
        City: 'Chicago',
        Zip: '60606',
        Country: 'USA',
        Contact: 'Bruce Wayne',
        Phone: '312-555-0114',
        DistrictManager: 'Alfred Pennyworth',
        Active: true,
        Latitude: 41.8781,
        Longitude: -87.6298,
        BuildingSqft: 45000,
        LotSqft: 20000,
        ParkingSpots: 50,
        YearBuilt: 1970,
        BlueprintUrl: { Description: 'Chicago Blueprint', Url: 'https://pdfobject.com/pdf/sample.pdf' },
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-10-06T13:45:00Z'
    },
    {
        Id: 15,
        Title: 'Springfield Plant',
        State: 'IL',
        Branch: 'Illinois South',
        Street: '742 Evergreen Terrace',
        City: 'Springfield',
        Zip: '62704',
        Country: 'USA',
        Contact: 'Homer Simpson',
        Phone: '217-555-0115',
        DistrictManager: 'Alfred Pennyworth',
        Active: true,
        Latitude: 39.7817,
        Longitude: -89.6501,
        BuildingSqft: 18000,
        LotSqft: 36000,
        ParkingSpots: 70,
        YearBuilt: 1992,
        BlueprintUrl: null,
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-09-28T10:10:00Z'
    },
    {
        Id: 16,
        Title: 'Seattle Headquarters',
        State: 'WA',
        Branch: 'PNW Region',
        Street: '999 3rd Ave',
        City: 'Seattle',
        Zip: '98104',
        Country: 'USA',
        Contact: 'Bill Gates',
        Phone: '206-555-0116',
        DistrictManager: 'Satya Nadella',
        Active: true,
        Latitude: 47.6062,
        Longitude: -122.3321,
        BuildingSqft: 50000,
        LotSqft: 100000,
        ParkingSpots: 300,
        YearBuilt: 2010,
        BlueprintUrl: { Description: 'Seattle Blueprint', Url: 'https://pdfobject.com/pdf/sample.pdf' },
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-10-15T09:00:00Z'
    },
    {
        Id: 17,
        Title: 'Spokane Warehouse',
        State: 'WA',
        Branch: 'PNW Region',
        Street: '500 E Sprague Ave',
        City: 'Spokane',
        Zip: '99202',
        Country: 'USA',
        Contact: 'Jeff Bezos',
        Phone: '509-555-0117',
        DistrictManager: 'Satya Nadella',
        Active: false,
        Latitude: 47.6588,
        Longitude: -117.4260,
        BuildingSqft: 30000,
        LotSqft: 60000,
        ParkingSpots: 120,
        YearBuilt: 2005,
        BlueprintUrl: null,
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-08-30T15:30:00Z'
    },
    {
        Id: 18,
        Title: 'Portland Office',
        State: 'OR',
        Branch: 'PNW Region',
        Street: '1000 SW Broadway',
        City: 'Portland',
        Zip: '97205',
        Country: 'USA',
        Contact: 'Phil Knight',
        Phone: '503-555-0118',
        DistrictManager: 'Satya Nadella',
        Active: true,
        Latitude: 45.5152,
        Longitude: -122.6784,
        BuildingSqft: 22000,
        LotSqft: 40000,
        ParkingSpots: 80,
        YearBuilt: 2014,
        BlueprintUrl: { Description: 'Portland Blueprint', Url: 'https://pdfobject.com/pdf/sample.pdf' },
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-10-11T11:00:00Z'
    },
    {
        Id: 19,
        Title: 'Phoenix Desert Hub',
        State: 'AZ',
        Branch: 'Southwest',
        Street: '200 E Washington St',
        City: 'Phoenix',
        Zip: '85004',
        Country: 'USA',
        Contact: 'Larry Fitzgerald',
        Phone: '602-555-0119',
        DistrictManager: 'Kurt Warner',
        Active: true,
        Latitude: 33.4484,
        Longitude: -112.0740,
        BuildingSqft: 35000,
        LotSqft: 70000,
        ParkingSpots: 150,
        YearBuilt: 2011,
        BlueprintUrl: null,
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-10-03T13:00:00Z'
    },
    {
        Id: 20,
        Title: 'Las Vegas Strip',
        State: 'NV',
        Branch: 'Southwest',
        Street: '3000 Las Vegas Blvd S',
        City: 'Las Vegas',
        Zip: '89109',
        Country: 'USA',
        Contact: 'Elvis Presley',
        Phone: '702-555-0120',
        DistrictManager: 'Kurt Warner',
        Active: true,
        Latitude: 36.1699,
        Longitude: -115.1398,
        BuildingSqft: 60000,
        LotSqft: 120000,
        ParkingSpots: 500,
        YearBuilt: 1998,
        BlueprintUrl: { Description: 'Vegas Blueprint', Url: 'https://pdfobject.com/pdf/sample.pdf' },
        FloorplanUrl: null,
        DocsFolderUrl: null,
        Modified: '2023-10-20T20:00:00Z'
    }
];
